# Generated by Django 5.1.3 on 2025-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to='media/assignments/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(upload_to='media/profile_pics/'),
        ),
    ]
