# Generated by Django 4.2.23 on 2025-07-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstaffs',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='notificationstaffs',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationstaffs',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='notificationstaffs',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationstaffs',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationstaffs',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationstaffs',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstaffs',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notification_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationstaffs',
            name='verb',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationstaffs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_datetime', models.DateTimeField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('STAFFS', 'Staff Only')], default='ALL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.sessionyearmodel')),
            ],
        ),
    ]
