# Generated by Django 5.1.3 on 2024-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='medical_history_id',
        ),
        migrations.AddField(
            model_name='students',
            name='asthmatic',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='blind',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='disabilities',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='drug_allergy',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='epilepsy',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='health_problems',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='hypertension',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='medication',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='mental_illness',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='sickle_cell',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='spectacle_use',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='tuberculosis',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
