# Generated by Django 4.0.6 on 2022-08-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresults',
            name='principal_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.principalcomment'),
        ),
    ]
