# Generated by Django 5.1.3 on 2025-07-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='staff_group',
        ),
        migrations.AddField(
            model_name='room',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.staffs'),
        ),
        migrations.AlterField(
            model_name='room',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class'),
        ),
    ]
