# Generated by Django 5.1.3 on 2025-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_assignment_file_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(upload_to='media/submitted_assignments/'),
        ),
    ]
