# Generated by Django 4.2.23 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_question_correct_text_answer_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('OPEN_ENDED', 'Open Ended')], max_length=20),
        ),
    ]
