# Generated by Django 4.2.23 on 2025-07-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_notificationstaffs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='session_year',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('HOLIDAY', 'Holiday'), ('RESULT', 'Result Release'), ('GENERAL', 'General'), ('ASSIGNMENT', 'Assignment Deadline')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.sessionyearmodel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All'), ('STUDENTS', 'Students'), ('STAFFS', 'Staffs')], max_length=20),
        ),
    ]
