# Generated by Django 4.0.6 on 2022-08-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_studentresults_principal_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrincipalComment',
            new_name='AdminComment',
        ),
        migrations.RenameField(
            model_name='studentresults',
            old_name='principal_id',
            new_name='admincomment_id',
        ),
    ]
