# Generated by Django 5.1.3 on 2024-11-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_students_age_alter_students_bus_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender_choice',
        ),
    ]
