# Generated by Django 4.0.6 on 2022-08-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_rename_principalcomment_admincomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresults',
            name='admincomment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.admincomment'),
        ),
    ]
