# Generated by Django 5.1.3 on 2025-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_room_staff_group_room_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='classroom',
            new_name='classroom_id',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
