# Generated by Django 4.2.23 on 2025-07-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstudent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='notificationstudent',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notification_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='verb',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
