# Generated by Django 4.0.6 on 2022-08-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_studentresults_admincomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresults',
            name='admincomment_id',
            field=models.CharField(max_length=225),
        ),
        migrations.DeleteModel(
            name='AdminComment',
        ),
    ]
