# Generated by Django 4.2.23 on 2025-07-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_alter_event_description_alter_event_related_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('EXAM', 'Exam'), ('HOLIDAY', 'Holiday'), ('RESULT', 'Result Release'), ('OTHER', 'Other')], default='EVENT', max_length=20),
        ),
    ]
