# Generated by Django 4.2.23 on 2025-07-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_alter_notificationstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='verb',
            field=models.CharField(max_length=255),
        ),
    ]
