"""add_timetable_entries

Revision ID: 612785094e7f
Revises: 001
Create Date: 2026-04-28 13:08:19.893497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '612785094e7f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('assignment_submissions', 'graded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_assignment_submissions_created_at'), 'assignment_submissions', ['created_at'], unique=False)
    op.drop_constraint('assignment_submissions_student_id_fkey', 'assignment_submissions', type_='foreignkey')
    op.drop_constraint('assignment_submissions_assignment_id_fkey', 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_submissions', 'assignments', ['assignment_id'], ['id'])
    op.create_foreign_key(None, 'assignment_submissions', 'student_profiles', ['student_id'], ['id'])
    op.alter_column('assignments', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_assignments_created_at'), 'assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignments_title'), 'assignments', ['title'], unique=False)
    op.drop_constraint('assignments_staff_id_fkey', 'assignments', type_='foreignkey')
    op.drop_constraint('assignments_subject_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'staff_profiles', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'subjects', ['subject_id'], ['id'])
    op.alter_column('attendance_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('attendance_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_attendance_records_created_at'), 'attendance_records', ['created_at'], unique=False)
    op.drop_constraint('attendance_records_session_id_fkey', 'attendance_records', type_='foreignkey')
    op.drop_constraint('attendance_records_student_id_fkey', 'attendance_records', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_records', 'attendance_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'attendance_records', 'student_profiles', ['student_id'], ['id'])
    op.alter_column('attendance_sessions', 'subject_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('attendance_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_attendance_sessions_created_at'), 'attendance_sessions', ['created_at'], unique=False)
    op.drop_constraint('attendance_sessions_subject_id_fkey', 'attendance_sessions', type_='foreignkey')
    op.drop_constraint('attendance_sessions_classroom_id_fkey', 'attendance_sessions', type_='foreignkey')
    op.drop_constraint('attendance_sessions_staff_id_fkey', 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_sessions', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'attendance_sessions', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'attendance_sessions', 'staff_profiles', ['staff_id'], ['id'])
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.alter_column('classrooms', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('classrooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('classrooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_classrooms_created_at'), 'classrooms', ['created_at'], unique=False)
    op.create_index(op.f('ix_classrooms_name'), 'classrooms', ['name'], unique=False)
    op.drop_constraint('classrooms_department_id_fkey', 'classrooms', type_='foreignkey')
    op.create_foreign_key(None, 'classrooms', 'departments', ['department_id'], ['id'])
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.alter_column('feedback_staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('feedback_staff', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_feedback_staff_created_at'), 'feedback_staff', ['created_at'], unique=False)
    op.drop_constraint('feedback_staff_staff_id_fkey', 'feedback_staff', type_='foreignkey')
    op.drop_constraint('feedback_staff_student_id_fkey', 'feedback_staff', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_staff', 'student_profiles', ['student_id'], ['id'])
    op.create_foreign_key(None, 'feedback_staff', 'staff_profiles', ['staff_id'], ['id'])
    op.alter_column('feedback_students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('feedback_students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_feedback_students_created_at'), 'feedback_students', ['created_at'], unique=False)
    op.drop_constraint('feedback_students_student_id_fkey', 'feedback_students', type_='foreignkey')
    op.drop_constraint('feedback_students_staff_id_fkey', 'feedback_students', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_students', 'staff_profiles', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'feedback_students', 'student_profiles', ['student_id'], ['id'])
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_requests', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_leave_requests_created_at'), 'leave_requests', ['created_at'], unique=False)
    op.drop_constraint('leave_requests_user_id_fkey', 'leave_requests', type_='foreignkey')
    op.drop_constraint('leave_requests_reviewed_by_id_fkey', 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'staff_profiles', ['reviewed_by_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.drop_constraint('notifications_recipient_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_sender_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.alter_column('quiz_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('quiz_attempts', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'graded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_quiz_attempts_created_at'), 'quiz_attempts', ['created_at'], unique=False)
    op.drop_constraint('quiz_attempts_quiz_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.drop_constraint('quiz_attempts_student_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'student_profiles', ['student_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.alter_column('quiz_results', 'marks_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('quiz_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('quiz_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_quiz_results_created_at'), 'quiz_results', ['created_at'], unique=False)
    op.drop_constraint('quiz_results_attempt_id_fkey', 'quiz_results', type_='foreignkey')
    op.drop_constraint('quiz_results_question_id_fkey', 'quiz_results', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_results', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'quiz_results', 'quiz_attempts', ['attempt_id'], ['id'])
    op.alter_column('quizzes', 'pass_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('quizzes', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('quizzes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_quizzes_created_at'), 'quizzes', ['created_at'], unique=False)
    op.create_index(op.f('ix_quizzes_title'), 'quizzes', ['title'], unique=False)
    op.drop_constraint('quizzes_staff_id_fkey', 'quizzes', type_='foreignkey')
    op.drop_constraint('quizzes_subject_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'quizzes', 'staff_profiles', ['staff_id'], ['id'])
    op.alter_column('session_years', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('session_years', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_session_years_created_at'), 'session_years', ['created_at'], unique=False)
    op.alter_column('staff_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('staff_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_staff_profiles_created_at'), 'staff_profiles', ['created_at'], unique=False)
    op.drop_constraint('staff_profiles_user_id_fkey', 'staff_profiles', type_='foreignkey')
    op.drop_constraint('staff_profiles_department_id_fkey', 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'staff_profiles', 'departments', ['department_id'], ['id'])
    op.alter_column('student_profiles', 'gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('student_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_student_profiles_created_at'), 'student_profiles', ['created_at'], unique=False)
    op.drop_constraint('student_profiles_session_year_id_fkey', 'student_profiles', type_='foreignkey')
    op.drop_constraint('student_profiles_classroom_id_fkey', 'student_profiles', type_='foreignkey')
    op.drop_constraint('student_profiles_user_id_fkey', 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'session_years', ['session_year_id'], ['id'])
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'student_profiles', 'classrooms', ['classroom_id'], ['id'])
    op.alter_column('subjects', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.drop_constraint('subjects_classroom_id_fkey', 'subjects', type_='foreignkey')
    op.drop_constraint('subjects_staff_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'subjects', 'staff_profiles', ['staff_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=254),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=254),
               existing_nullable=False)
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_staff_id_fkey', 'subjects', 'staff_profiles', ['staff_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('subjects_classroom_id_fkey', 'subjects', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.alter_column('subjects', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('subjects', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('subjects', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key('student_profiles_user_id_fkey', 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('student_profiles_classroom_id_fkey', 'student_profiles', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('student_profiles_session_year_id_fkey', 'student_profiles', 'session_years', ['session_year_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_student_profiles_created_at'), table_name='student_profiles')
    op.alter_column('student_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('student_profiles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('student_profiles', 'gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.create_foreign_key('staff_profiles_department_id_fkey', 'staff_profiles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('staff_profiles_user_id_fkey', 'staff_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_staff_profiles_created_at'), table_name='staff_profiles')
    op.alter_column('staff_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('staff_profiles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_session_years_created_at'), table_name='session_years')
    op.alter_column('session_years', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('session_years', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_subject_id_fkey', 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('quizzes_staff_id_fkey', 'quizzes', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_created_at'), table_name='quizzes')
    op.alter_column('quizzes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quizzes', 'due_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('quizzes', 'pass_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.create_foreign_key('quiz_results_question_id_fkey', 'quiz_results', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('quiz_results_attempt_id_fkey', 'quiz_results', 'quiz_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_quiz_results_created_at'), table_name='quiz_results')
    op.alter_column('quiz_results', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quiz_results', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quiz_results', 'marks_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('quiz_attempts_student_id_fkey', 'quiz_attempts', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('quiz_attempts_quiz_id_fkey', 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_quiz_attempts_created_at'), table_name='quiz_attempts')
    op.alter_column('quiz_attempts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'graded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.alter_column('questions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('questions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_sender_id_fkey', 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('notifications_recipient_id_fkey', 'notifications', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key('leave_requests_reviewed_by_id_fkey', 'leave_requests', 'staff_profiles', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('leave_requests_user_id_fkey', 'leave_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_leave_requests_created_at'), table_name='leave_requests')
    op.alter_column('leave_requests', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('leave_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('leave_requests', 'reviewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'feedback_students', type_='foreignkey')
    op.drop_constraint(None, 'feedback_students', type_='foreignkey')
    op.create_foreign_key('feedback_students_staff_id_fkey', 'feedback_students', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('feedback_students_student_id_fkey', 'feedback_students', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feedback_students_created_at'), table_name='feedback_students')
    op.alter_column('feedback_students', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('feedback_students', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'feedback_staff', type_='foreignkey')
    op.drop_constraint(None, 'feedback_staff', type_='foreignkey')
    op.create_foreign_key('feedback_staff_student_id_fkey', 'feedback_staff', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('feedback_staff_staff_id_fkey', 'feedback_staff', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feedback_staff_created_at'), table_name='feedback_staff')
    op.alter_column('feedback_staff', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('feedback_staff', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.create_unique_constraint('departments_name_key', 'departments', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('departments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.create_foreign_key('classrooms_department_id_fkey', 'classrooms', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_classrooms_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_created_at'), table_name='classrooms')
    op.alter_column('classrooms', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('classrooms', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('classrooms', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.alter_column('audit_logs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key('attendance_sessions_staff_id_fkey', 'attendance_sessions', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('attendance_sessions_classroom_id_fkey', 'attendance_sessions', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('attendance_sessions_subject_id_fkey', 'attendance_sessions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_attendance_sessions_created_at'), table_name='attendance_sessions')
    op.alter_column('attendance_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('attendance_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('attendance_sessions', 'subject_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.create_foreign_key('attendance_records_student_id_fkey', 'attendance_records', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('attendance_records_session_id_fkey', 'attendance_records', 'attendance_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_records_created_at'), table_name='attendance_records')
    op.alter_column('attendance_records', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('attendance_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_subject_id_fkey', 'assignments', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('assignments_staff_id_fkey', 'assignments', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assignments_title'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_at'), table_name='assignments')
    op.alter_column('assignments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('assignments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('assignments', 'due_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key('assignment_submissions_assignment_id_fkey', 'assignment_submissions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('assignment_submissions_student_id_fkey', 'assignment_submissions', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assignment_submissions_created_at'), table_name='assignment_submissions')
    op.alter_column('assignment_submissions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'graded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
