"""add_feedback_chat_tables

Revision ID: 78d340fe1bfb
Revises: 612785094e7f
Create Date: 2026-05-06 11:53:56.957410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78d340fe1bfb'
down_revision: Union[str, None] = '612785094e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
